      SUBROUTINE BOXCAR (YIN, YOUT, NPTS, SMWIDTH)
      IMPLICIT NONE
      REAL*8  YIN(8192), YOUT(8192), YMOVINGMEAN
      INTEGER I, ILO, IHI
      INTEGER NPTS
      INTEGER SMWIDTH, HSMWIDTH
*
      HSMWIDTH = SMWIDTH/2
      DO I = 1, NPTS
          ILO = MAX(I-HSMWIDTH,1)
          IHI = MIN(I+HSMWIDTH,NPTS)
          YOUT(I) = YMOVINGMEAN(YIN,ILO,IHI)
      END DO
      RETURN
      END
*
      REAL*8 FUNCTION YMOVINGMEAN(YIN,ILO,IHI)
      IMPLICIT NONE
      REAL*8 YIN(8192)
      INTEGER I
      INTEGER ILO
      INTEGER IHI
      YMOVINGMEAN = 0.0
      DO I = ILO, IHI
         YMOVINGMEAN = YMOVINGMEAN + YIN(I)
      END DO
      YMOVINGMEAN = YMOVINGMEAN / (IHI-ILO+1)
      RETURN
      END
      
      
      
      