/*This program takes a modified log file from LINES and
extracts a summary of each set of observations on a source.

The output file is of the form
Filename,Source_ID,North,South,East,West,Start,Stop,Date,Scan,Tsys
where 
North,South,East, West denote which spectra in the file holding the pointing observations,
Start,Stop; denote the spectra containing the on-source observations,
Date is the date on which the observation was made,
Scan is the number of the last on-source scan
 
The output from this program will be used to generate reduction scripts for
LINES. It also serves as a master log of all monitoring observations made.

The input file will be generated by the LINES procedure "la"

*/


#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>


void main(void)
{
	FILE *fp_log,*fp_out;
	fpos_t curpos;
	int end_src, count, old_count;
	double north, south, east, west, start, end, scan_num, old_scan_num;
	char line[500];
	char *file, *spectra, *name, *direction, *date, *scan, *tsys, *endptr;
	char *N=" N", *S=" S", *E=" E", *W=" W", *EW="EW", *NS="NS", *ON="ON";
	char sep[] = ",";
	char old_name[30], old_date[30], old_scan[30], old_file[30], old_tsys[30];



	fp_log = fopen("lines.fla", "r");
	fp_out = fopen("observations.txt", "a");
	while (fgets(line, 80, fp_log)!=NULL)
	{
                file = strtok(line,sep);
		spectra = strtok(NULL, sep);
		name = strtok(NULL, sep);
		direction = strtok(NULL, sep);
		date = strtok(NULL, sep);
		scan = strtok(NULL, sep);
                tsys = strtok(NULL,sep);

		end_src = 0;
		north = 0;
		south = 0;
		east = 0;
		west = 0;
		count = 0;
		old_count = 0;

		while (end_src != 1)
		{
			/* Find out where the different types of observations are stored*/
			if (strcmp(direction, N)==0)
				north = strtod(spectra, &endptr);
			if (strcmp(direction,S)==0)
				south = strtod(spectra, &endptr);
			if (strcmp(direction,E)==0)
				east =  strtod(spectra, &endptr);
			if (strcmp(direction, W)==0)
				west =  strtod(spectra, &endptr);
			if (strcmp(direction,NS)==0)
			{
				north = strtod(spectra, &endptr);
				south = strtod(spectra, &endptr);
			}
			if (strcmp(direction, EW)==0)
			{
				east = strtod(spectra, &endptr);
				west =  strtod(spectra, &endptr);
			}
			if (strcmp(direction,ON)==0)
			{
				if (count==0)
					start = strtod(spectra, &endptr);
				count++;
			}
			strcpy(old_name,name);  /*For checking if we are      */
			strcpy(old_date,date);  /*on a new source             */
			strcpy(old_scan,scan);  /*and if we are then          */
                        strcpy(old_tsys,tsys);  /*we will lose this           */
                        strcpy(old_file,file);  /*information.                 */
			fgetpos(fp_log,&curpos);/*This line will have         */
                                                /*to be reread if new source  */
			if (fgets(line, 80, fp_log)!=NULL)
			{
				file = strtok(line,sep);
				spectra = strtok(NULL, sep);
				name = strtok(NULL, sep);
				direction = strtok(NULL, sep);
				date = strtok(NULL, sep);
				scan = strtok(NULL, sep);
                		tsys = strtok(NULL,sep);

				scan_num = strtod(scan, &endptr);
                                old_scan_num = strtod(old_scan, &endptr);

				/* The comparisons below are only necessary   */
				/* when count>0 because then we are dealing   */
				/* with the on-source observations            */
                                /* and need to know when to stop              */

				/* Are we on a new source?                    */
				if (strcmp(file,old_file)!=0)
				    end_src = 1;   /*The source name changed*/

				/*new set of observations on same source*/
				if(((strcmp(direction, N)==0)||(strcmp(direction, NS)==0))
				                &&(count>0))
					end_src = 1;  /* started with new pointing */
				if (((scan_num-old_scan_num)>1)&&(strcmp(name,old_name)==0)
				                &&(count>0))
					end_src = 1; /*the observations are not consecutive*/

			}
			else    /* End of file */
				end_src = 1;
		}
		end = start + count - 1;

		/*write the strings from the previous line read because            */
                /*the new strings have been read from the line for the next source */
		printf("%s %s  %.0f  %.0f  %.0f  %.0f  %.0f  %.0f %s %s %s",
		       old_file, old_name, north, south, east, west, start, end,
		       old_date, old_scan, old_tsys);
		fprintf(fp_out, "%s,%s,%.0f,%.0f,%.0f,%.0f,%.0f,%.0f,%s,%s,%s",
			old_file, old_name, north, south, east, west, start,
			end, old_date, old_scan, old_tsys);

		fsetpos(fp_log,&curpos); /* Go back to previous line in input file*/
	}
	fclose(fp_log);
	fclose(fp_out);
}
